import boto
import boto.s3.connection

"""
 The txt files look like:


     0041ce35
     068d74fd
     06e599eb
     0aecedcb
     0e4a9f38
     12823619
     158dcac4
     19951956
     1add9e78
     1d56fd6e
     1ffdd43e
     2856fdbe
     2eafa76f
     3205ee25
     3260e194
     3777dc90
     38fa89f6
     3b2a209d
     ...


They are generated by running the following command on an ingestion machine with
access to /mnt/RCP_DEV/bundle/[du]

$find . -maxdepth 3 | awk 'BEGIN {FS="/"} {print $4}' | awk 'NF > 0' | sort -u

"""

conn = boto.connect_s3(
        aws_access_key_id = access_key,
        aws_secret_access_key = secret_key,
        host = 's3.amazonaws.com',
        #is_secure=False,               # uncommmnt if you are not using ssl
        calling_format = boto.s3.connection.OrdinaryCallingFormat(),
        )
# all buckets
#bucket = conn.get_bucket('rcp_d_minor')
buckets = [conn.get_bucket('rcp_d_minor'), conn.get_bucket('rcp_d_major')]

for bucket in buckets:
    with open('du_241.txt') as f:
    #with open('du_536.txt') as f:
        for line in f:
            k = line.strip()
            if k:
                I = bucket.list(prefix = k)
                L = list(I)
                #key = bucket.delete_key(k)
                
                print "Deleted: %s, %s" % (L, bucket.name)
                bucket.delete_keys(L, quiet = True)
